name: release-binary

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - 
        name: generate prod env.yaml
        run: |
          make prodenv && \
          echo "commit_code: $(git rev-list -1 HEAD)" >> commit
      - 
        name: fyne-cross
        run: |
          version=$(git describe --tags --abbrev=0 | sed 's/v//g') &&\
          go install github.com/fyne-io/fyne-cross@latest && \
          fyne-cross linux --pull -app-version $version && \
          fyne-cross windows --pull -app-version $version
      - 
        name: generate checksum
        run: |
          shasum -a 512 fyne-cross/dist/linux-amd64/* > linux-amd64-checksum && \
          shasum -a 512 fyne-cross/dist/windows-amd64/* > windows-amd64-checksum
      - 
        name: tar files
        run: |
          tar zcvf linux-amd64.tar.gz fyne-cross/dist/linux-amd64/ linux-amd64-checksum commit && \
          tar zcvf windows-amd64.tar.gz fyne-cross/dist/windows-amd64/ windows-amd64-checksum commit
      - 
        name: github push release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.tar.gz"
          bodyFile: "readme.md"
          token: ${{ secrets.RELEASE }}