name: release-binary

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - 
        name: download fyne
        run: |
          go install github.com/fyne-io/fyne-cross@latest && \
          fyne-cross linux --pull
      -
        name: Upload assets
        uses: actions/upload-artifact@v2
        with:
          name: myapp
          path: fyne-cross/*