name: release-binary

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - 
        name: fyne-cross
        run: |
          version=$(git describe --tags --abbrev=0) &&\
          go install github.com/fyne-io/fyne-cross@latest && \
          fyne-cross linux --pull -app-version $version && \
          fyne-cross windows --pull -app-version $version
      - 
        name: generate checksum
        run: |
          shasum -a 512 fyne-cross/dist/linux-amd64/* > linux-amd64-checksum && \
          shasum -a 512 fyne-cross/dist/windows-amd64/* > windows-amd64-checksum
      - 
        name: tar fyne-cross output
        run: |
          tar zcvf linux-amd64.tar.gz fyne-cross/dist/linux-amd64/ linux-amd64-checksum && \
          tar zcvf windows-amd64.tar.gz fyne-cross/dist/windows-amd64/ windows-amd64-checksum
      - 
        name: github release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.tar.gz,*checksum"
          bodyFile: "readme.md" # release 時的說明檔案
          token: ${{ secrets.RELEASE }}