name: "staticcheck"
on: 
  push:
    branches:
      - master
    paths:
      - '.github/workflows/staticcheck.yml'
      - 'config/**'
      - 'module/**'
      - 'view/**'
      - 'main.go'

jobs:
  ci:
    name: "staticcheck"
    strategy:
      fail-fast: false
      matrix:
        os:  ["windows-latest", "ubuntu-latest", "macOS-latest"]
        go:  ["1.19.x"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: WillAbides/setup-go-faster@v1.7.0
      with:
        go-version: ${{ matrix.go }}
    - run: "go vet ./..."
    - uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2022.1"
        install-go: false
        cache-key: ${{ matrix.go }}